# basic deployment, use overlay\kustomization.yaml to configure deployment

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - ingress.yaml
  - config-storage.yaml
  - media-storage.yaml
  - service.yaml
